"""The enemies the levels send.

The easy ones first, the ones on the ground, the difficulty each one comes at, and the formations each one flies in.
"""

from typing import Any

WARM_UP = ("drone", "weaver", "dart", "mite")  # easy first waves
GROUND = frozenset({"turret", "flak_cannon"})  # roll on the ground
# The difficulty each enemy first comes at.
UNLOCK = {
    "dart": 1,
    "diver": 1,
    "drone": 1,
    "gunship": 1,
    "mite": 1,
    "weaver": 1,
    "imp": 2,
    "rocketeer": 2,
    "sniper": 2,
    "spark": 2,
    "swarmer": 2,
    "tick": 2,
    "hornet": 3,
    "serpent": 3,
    "catamaran": 3,
    "albatross": 4,
    "buckshot": 4,
    "mine_layer": 5,
    "shield_carrier": 5,
    "splitter": 5,
    "turret": 5,
    "flak_cannon": 5,
    "hunter": 5,
    "kestrel": 5,
    "stalker": 5,
    "rapier": 6,
    "scrapper": 6,
    "outrider": 6,
    "bomber": 7,
    "needle": 7,
    "wisp": 7,
    "freighter": 7,
    "lancer": 9,
    "manta": 9,
    "broadside": 10,
    "javelin": 10,
    "harrier": 10,
    "brood": 11,
    "brawler": 11,
    "howitzer": 12,
    "rampart": 13,
    "condor": 14,
    "warhawk": 15,
    "stormcrow": 17,
    "pincer": 18,
    "behemoth": 18,
}
# How each enemy's groups come (a wave without its time and enemy); `count` is the group's size at difficulty 1,
# multiplied by GROWTH for each step above it.
SHAPES: dict[str, tuple[dict[str, Any], ...]] = {
    "albatross": (
        {"x": -0.33, "count": 0.84},
        {"x": 0.33, "count": 0.79},
    ),
    "behemoth": (
        {"x": 0.0, "count": 0.31},
        {"x": 0.33, "count": 0.28},
    ),
    "bomber": (
        {"formation": "column", "side": "right", "y": 0.66, "count": 0.68},
        {"formation": "column", "side": "right", "y": 0.74, "count": 0.49},
        {"formation": "column", "side": "left", "y": 0.59, "count": 0.49},
        {"formation": "column", "side": "left", "y": 0.65, "count": 0.42},
        {"formation": "column", "side": "right", "y": 0.59, "count": 0.41},
        {"formation": "column", "side": "right", "y": 0.65, "count": 0.38},
        {"formation": "column", "side": "left", "y": 0.6, "count": 0.37},
        {"formation": "column", "side": "right", "y": 0.68, "count": 0.33},
        {"formation": "column", "side": "left", "y": 0.67, "count": 0.32},
        {"formation": "column", "side": "left", "y": 0.58, "count": 0.31},
        {"formation": "column", "side": "left", "y": 0.69, "count": 0.28},
        {"formation": "column", "side": "left", "y": 0.71, "count": 0.26},
    ),
    "brawler": (
        {"x": -0.33, "count": 0.5},
        {"x": 0.5, "count": 0.41},
    ),
    "broadside": (
        {"formation": "column", "interval": 1.2, "side": "right", "y": 0.45, "count": 0.47},
        {"formation": "column", "interval": 1.2, "side": "left", "y": 0.45, "count": 0.36},
    ),
    "brood": (
        {"x": 0.33, "count": 0.52},
        {"x": 0.5, "count": 0.38},
    ),
    "buckshot": ({"formation": "line", "spacing": 1.33, "x": 0.0, "count": 0.93},),
    "catamaran": ({"formation": "line", "spacing": 1.17, "x": 0.0, "count": 1.66},),
    "condor": ({"x": 0.0, "count": 0.35},),
    "dart": (
        {"formation": "column", "interval": 0.4, "x": -0.5, "count": 4.0},
        {"formation": "column", "interval": 0.4, "x": 0.58, "count": 3.73},
        {"formation": "column", "interval": 0.35, "x": -0.5, "count": 3.54},
    ),
    "diver": (
        {"formation": "line", "spacing": 0.83, "count": 3.0},
        {"formation": "line", "spacing": 0.58, "count": 2.63},
        {"formation": "line", "spacing": 0.5, "count": 3.87},
    ),
    "drone": (
        {"formation": "column", "x": -0.67, "count": 5.0},
        {"formation": "column", "x": 0.67, "count": 5.0},
        {"formation": "line", "count": 5.04},
        {"formation": "line", "spacing": 0.5, "count": 4.0},
        {"formation": "column", "interval": 0.45, "x": -0.67, "count": 3.39},
        {"formation": "column", "interval": 0.45, "x": 0.67, "count": 3.39},
        {"formation": "line", "spacing": 0.33, "count": 4.27},
        {"formation": "column", "x": 0.0, "count": 3.04},
    ),
    "flak_cannon": (
        {"formation": "line", "spacing": 1.17, "x": 0.0, "count": 1.29},
        {"formation": "line", "spacing": 1.32, "x": 0.0, "count": 0.89},
        {"formation": "line", "spacing": 1.1, "x": 0.0, "count": 1.47},
        {"formation": "line", "spacing": 1.42, "x": 0.0, "count": 1.0},
        {"formation": "line", "spacing": 1.37, "x": 0.0, "count": 1.32},
        {"formation": "line", "spacing": 1.15, "x": 0.0, "count": 1.28},
        {"formation": "line", "spacing": 1.33, "x": 0.0, "count": 0.88},
        {"formation": "line", "spacing": 1.22, "x": 0.0, "count": 0.77},
        {"formation": "line", "spacing": 1.05, "x": 0.0, "count": 0.78},
        {"formation": "line", "spacing": 1.2, "x": 0.0, "count": 0.79},
        {"formation": "line", "spacing": 1.48, "x": 0.0, "count": 0.76},
        {"formation": "line", "spacing": 1.08, "x": 0.0, "count": 0.64},
        {"formation": "line", "spacing": 1.18, "x": 0.0, "count": 0.62},
        {"formation": "line", "spacing": 1.28, "x": 0.0, "count": 0.6},
        {"formation": "line", "spacing": 1.25, "x": 0.0, "count": 0.56},
    ),
    "freighter": (
        {"x": -0.5, "count": 0.66},
        {"x": 0.5, "count": 0.6},
    ),
    "gunship": (
        {"formation": "column", "x": 0.0, "count": 0.85},
        {"formation": "line", "spacing": 1.33, "count": 0.85},
    ),
    "harrier": (
        {"x": 0.0, "count": 0.54},
        {"x": -0.33, "count": 0.45},
        {"formation": "line", "spacing": 1.5, "x": 0.0, "count": 0.62},
    ),
    "hornet": (
        {"formation": "column", "interval": 0.9, "x": -0.33, "count": 2.71},
        {"formation": "column", "interval": 0.9, "x": 0.5, "count": 2.44},
        {"formation": "column", "interval": 0.9, "x": 0.0, "count": 1.92},
    ),
    "howitzer": (
        {"x": 0.5, "count": 0.49},
        {"x": -0.5, "count": 0.38},
    ),
    "hunter": (
        {"formation": "column", "x": -0.45, "count": 0.76},
        {"formation": "column", "x": 0.33, "count": 0.71},
        {"formation": "column", "x": 0.3, "count": 0.66},
        {"formation": "column", "x": 0.02, "count": 0.64},
        {"formation": "column", "x": -0.4, "count": 0.41},
        {"formation": "column", "x": -0.18, "count": 0.45},
        {"formation": "column", "x": -0.07, "count": 0.44},
        {"formation": "column", "x": -0.58, "count": 0.37},
        {"formation": "column", "x": 0.15, "count": 0.33},
        {"formation": "column", "x": 0.28, "count": 0.32},
        {"formation": "column", "x": 0.35, "count": 0.3},
        {"formation": "column", "x": -0.15, "count": 0.29},
    ),
    "imp": (
        {"formation": "line", "spacing": 0.75, "x": 0.0, "count": 2.67},
        {"formation": "line", "spacing": 0.67, "x": 0.0, "count": 2.15},
    ),
    "javelin": (
        {"formation": "column", "interval": 1.5, "x": 0.5, "count": 0.98},
        {"formation": "column", "interval": 1.5, "x": -0.5, "count": 0.94},
    ),
    "kestrel": (
        {"formation": "column", "interval": 1.2, "side": "left", "y": 0.6, "count": 1.28},
        {"formation": "column", "interval": 1.2, "side": "right", "y": 0.55, "count": 1.32},
    ),
    "lancer": (
        {"formation": "column", "x": -0.15, "count": 0.58},
        {"formation": "column", "x": 0.58, "count": 0.52},
        {"formation": "column", "x": -0.7, "count": 0.5},
        {"formation": "column", "x": -0.63, "count": 0.45},
        {"formation": "column", "x": 0.08, "count": 0.44},
        {"formation": "column", "x": 0.07, "count": 0.4},
        {"formation": "column", "x": -0.47, "count": 0.34},
        {"formation": "column", "x": -0.55, "count": 0.3},
    ),
    "manta": (
        {"formation": "column", "interval": 1.2, "side": "left", "y": 0.5, "count": 0.46},
        {"formation": "column", "interval": 1.2, "side": "right", "y": 0.5, "count": 0.49},
    ),
    "mine_layer": (
        {"formation": "column", "side": "left", "y": 0.6, "count": 0.54},
        {"formation": "column", "side": "right", "y": 0.4, "count": 0.46},
        {"formation": "column", "side": "left", "y": 0.7, "count": 0.54},
        {"formation": "column", "side": "right", "y": 0.3, "count": 0.51},
        {"formation": "column", "side": "left", "y": 0.5, "count": 0.47},
        {"formation": "column", "side": "right", "y": 0.5, "count": 0.42},
        {"formation": "column", "side": "left", "y": 0.3, "count": 0.4},
        {"formation": "column", "side": "right", "y": 0.6, "count": 0.39},
        {"formation": "column", "side": "left", "y": 0.4, "count": 0.34},
        {"formation": "column", "side": "right", "y": 0.7, "count": 0.36},
    ),
    "mite": (
        {"formation": "line", "spacing": 0.75, "x": 0.0, "count": 2.85},
        {"formation": "line", "spacing": 0.67, "x": 0.0, "count": 1.75},
    ),
    "needle": (
        {"x": 0.0, "count": 0.68},
        {"x": 0.33, "count": 0.47},
    ),
    "outrider": ({"formation": "line", "spacing": 1.33, "x": 0.0, "count": 1.3},),
    "pincer": (
        {"x": 0.0, "count": 0.32},
        {"x": -0.33, "count": 0.28},
    ),
    "rampart": (
        {"x": 0.0, "count": 0.44},
        {"x": -0.33, "count": 0.37},
        {"x": 0.5, "count": 0.3},
    ),
    "rapier": (
        {"formation": "column", "interval": 1.0, "x": 0.5, "count": 1.47},
        {"formation": "column", "interval": 0.8, "x": -0.5, "count": 1.85},
        {"formation": "column", "interval": 0.8, "x": 0.5, "count": 0.96},
    ),
    "rocketeer": ({"formation": "line", "spacing": 1.17, "x": 0.0, "count": 1.11},),
    "scrapper": ({"formation": "line", "spacing": 0.83, "x": 0.0, "count": 1.64},),
    "serpent": (
        {"formation": "column", "interval": 0.8, "x": -0.43, "count": 2.71},
        {"formation": "column", "interval": 0.8, "x": 0.12, "count": 2.61},
        {"formation": "column", "interval": 0.8, "x": -0.58, "count": 2.36},
        {"formation": "column", "interval": 0.8, "x": 0.1, "count": 2.28},
        {"formation": "column", "interval": 0.8, "x": -0.72, "count": 1.92},
        {"formation": "column", "interval": 0.8, "x": 0.0, "count": 1.73},
        {"formation": "column", "interval": 0.8, "x": 0.7, "count": 1.51},
        {"formation": "column", "interval": 0.8, "x": -0.23, "count": 1.46},
        {"formation": "column", "interval": 0.8, "x": -0.75, "count": 1.41},
        {"formation": "column", "interval": 0.8, "x": -0.25, "count": 1.23},
        {"formation": "column", "interval": 0.8, "x": -0.45, "count": 1.19},
        {"formation": "column", "interval": 0.8, "x": 0.67, "count": 1.03},
        {"formation": "column", "interval": 0.8, "x": -0.28, "count": 0.96},
        {"formation": "column", "interval": 0.8, "x": -0.38, "count": 0.87},
        {"formation": "column", "interval": 0.8, "x": 0.57, "count": 0.84},
        {"formation": "column", "interval": 0.8, "x": 0.48, "count": 0.81},
        {"formation": "column", "interval": 0.8, "x": -0.6, "count": 0.78},
    ),
    "shield_carrier": (
        {"formation": "column", "x": 0.0, "count": 0.79},
        {"formation": "line", "spacing": 1.33, "count": 0.84},
    ),
    "sniper": (
        {"formation": "line", "spacing": 1.67, "count": 0.93},
        {"formation": "column", "x": 0.0, "count": 0.77},
    ),
    "spark": (
        {"formation": "column", "interval": 0.3, "x": 0.67, "count": 4.83},
        {"formation": "column", "interval": 0.3, "x": -0.67, "count": 4.21},
        {"formation": "column", "interval": 0.3, "x": 0.0, "count": 2.37},
    ),
    "splitter": (
        {"formation": "line", "spacing": 1.33, "count": 1.57},
        {"formation": "column", "interval": 1.5, "x": 0.0, "count": 2.36},
        {"formation": "line", "spacing": 0.83, "count": 1.6},
    ),
    "stalker": (
        {"formation": "line", "spacing": 1.33, "x": 0.0, "count": 1.4},
        {"formation": "line", "spacing": 0.83, "x": 0.0, "count": 1.07},
    ),
    "stormcrow": (
        {"x": 0.0, "count": 0.33},
        {"x": -0.33, "count": 0.3},
        {"x": 0.33, "count": 0.26},
    ),
    "swarmer": (
        {"formation": "column", "interval": 0.2, "side": "left", "y": 0.4, "count": 4.78},
        {"formation": "column", "interval": 0.2, "side": "right", "y": 0.4, "count": 4.78},
        {"formation": "column", "interval": 0.2, "side": "left", "y": 0.6, "count": 5.09},
        {"formation": "column", "interval": 0.2, "side": "right", "y": 0.6, "count": 5.09},
        {"formation": "column", "interval": 0.2, "side": "left", "y": 0.3, "count": 5.34},
        {"formation": "column", "interval": 0.2, "side": "right", "y": 0.3, "count": 5.34},
        {"formation": "column", "interval": 0.2, "side": "left", "y": 0.5, "count": 5.16},
        {"formation": "column", "interval": 0.2, "side": "right", "y": 0.5, "count": 5.16},
    ),
    "tick": (
        {"formation": "line", "spacing": 0.83, "x": 0.0, "count": 2.71},
        {"formation": "line", "spacing": 0.67, "x": 0.0, "count": 2.01},
    ),
    "turret": (
        {"formation": "line", "spacing": 1.67, "count": 1.42},
        {"formation": "line", "spacing": 1.0, "count": 1.13},
        {"formation": "line", "spacing": 0.83, "count": 1.11},
    ),
    "warhawk": (
        {"x": 0.0, "count": 0.34},
        {"x": 0.33, "count": 0.34},
    ),
    "weaver": (
        {"formation": "column", "interval": 0.4, "x": 0.0, "count": 5.09},
        {"formation": "column", "interval": 0.4, "x": -0.58, "count": 4.25},
        {"formation": "column", "interval": 0.4, "x": 0.58, "count": 4.25},
        {"formation": "column", "interval": 0.35, "x": 0.0, "count": 8.0},
        {"formation": "column", "interval": 0.38, "x": -0.67, "count": 5.14},
        {"formation": "column", "interval": 0.38, "x": 0.67, "count": 4.97},
        {"formation": "column", "interval": 0.38, "x": 0.0, "count": 4.81},
        {"formation": "column", "interval": 0.4, "x": -0.67, "count": 3.8},
        {"formation": "column", "interval": 0.4, "x": 0.67, "count": 3.8},
    ),
    "wisp": (
        {"formation": "line", "spacing": 1.33, "x": 0.0, "count": 1.37},
        {"formation": "line", "spacing": 0.83, "x": 0.0, "count": 1.32},
    ),
}
